// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Colo: typeof import('./src/components/views/dashboard/colo.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    DashBoard: typeof import('./src/components/views/dashboard/DashBoard.vue')['default']
    Globe: typeof import('./src/components/views/dashboard/Globe.vue')['default']
    MousePos: typeof import('./src/components/MousePos.vue')['default']
    Network: typeof import('./src/components/views/dashboard/Network.vue')['default']
    Placeholder: typeof import('./src/components/views/dashboard/Placeholder.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
